name: test git ref workflow

on:
  push:
    branches:
      - testing-git-ref

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest tag
        run: |
          TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Print TAG
        run: echo ${{ env.TAG }}

