name: Version Bump

on:
  push:
    branches:
      - 2.6

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Version Bump
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Tag and Version Information
        id: version-bump
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f3)
          MINOR_PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f4)
          BASE="$MAJOR_VERSION.$MINOR_VERSION"
          BASE_X="$MAJOR_VERSION.x"
          CURRENT_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.$MINOR_PATCH_VERSION"
          CURRENT_VERSION_SHORT="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
          NEW_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$((PATCH_VERSION+1)).$MINOR_PATCH_VERSION"
          NEW_VERSION_SHORT="$MAJOR_VERSION.$MINOR_VERSION.$((PATCH_VERSION+1))"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "BASE_X=$BASE_X" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION_SHORT=$CURRENT_VERSION_SHORT" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION_SHORT=$NEW_VERSION_SHORT" >> $GITHUB_ENV

      - name: Increment Patch Version
        run: |
          sed -i'' -e "s/\"version\": \"$CURRENT_VERSION\",/\"version\": \"$NEW_VERSION\",/g" opensearch_dashboards.json
          sed -i'' -e "s/\"opensearchDashboardsVersion\": \"$CURRENT_VERSION_SHORT\",/\"version\": \"$NEW_VERSION_SHORT\",/g" opensearch_dashboards.json
          sed -i'' -e "s/\"version\": \"$CURRENT_VERSION\",/\"version\": \"$NEW_VERSION\",/g" package.json
          echo Adding $NEW_VERSION after $CURRENT_VERSION
          echo Adding $NEW_VERSION_SHORT after $CURRENT_VERSION_SHORT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ${{ env.BASE }}
          branch: 'create-pull-request/patch-${{ env.BASE }} '
          delete-branch: true
          commit-message: Increment version to ${{ env.NEW_VERSION }}
          signoff: true
          labels: |
            autocut
          title: '[AUTO] Increment version to ${{ env.NEW_VERSION }}.'
          body: |
            I've noticed that a new tag ${{ env.CURRENT_VERSION }} was pushed, and incremented the version from ${{ env.CURRENT_VERSION }} to ${{ env.NEW_VERSION }}.
